name: fxml
channels:
  - conda-forge
  - nvidia
  - defaults
dependencies:
  - python=3.11
  - pytorch
  - lightning
  - numpy
  - pandas
  - matplotlib
  - tqdm
  - yaml
  - tensorboard
  - joblib
  - scikit-learn
  - jupyter
  - seaborn
  - pip
  - sqlite
  - mplfinance
  - ta
  - TA-Lib
  - pip:
      - MetaTrader5
      - mqpy
      - backtesting
