# Configuration for forex prediction experiments

# Data configuration (preparation phase)
data:
  raw: data/raw/dukascopy-eurusd-tick-2020-01-01-2024-12-31.csv

# Resampling configuration
resampling:
  type: time # 'time' or 'dollar'
  minutes: 10 # For time-based resampling
  threshold: 421558000000 # For dollar bar resampling
  symbol: "USDJPY"
  date_range:
    start_date: "20240101" # Format: YYYYMMDD
    end_date: "20241231" # Format: YYYYMMDD
  output:
    dir: data/resampled
    prefix: bars

events:
  # Event sampling configuration
  type: Z-SCORE-W100-1Z # 'cusum' or 'volatility'
  # type: CUSUM_0.00033 # 'cusum' or 'volatility'
  threshold: 2.52e-04 # CUSUM threshold for event detection

# Labeling configuration
labeling:
  type: TB # 'TB' or 'Z'
  # Volatility calculation
  volatility:
    method: atr # 'atr' or 'daily_vol'
    atr_window: 20
    daily_vol_span: 100
  z: 0.4
  # Triple barrier parameters
  barriers:
    pt_sl_multipliers: [1.0, 1.0] # [profit_taking, stop_loss]
    vertical_barrier_minutes: 120 # Minutes for time-based exit
    min_ret_factor: 0.5 # Minimum return threshold as factor of mean target

  # Processing parameters
  processing:
    num_threads: 20
    intraday_only: true # Keep only intraday events

  # Output settings
  output:
    dir: data/direction_labels
    suffix: direction_labels

# Preprocessing configuration
preprocessing:
  # Feature engineering settings
  features:
    add_returns: true
    add_technical_indicators: true
    add_time_features: true

    # Technical indicator settings
    technical_indicators:
      rv_windows: [5, 15, 50]
      ema_windows: [5, 20, 50, 100]
      atr_windows: [14, 60, 120]
      adx_windows: [14]
      bollinger_bands:
        window: 20
        window_dev: 2
      donchian_channel_windows: [20, 50, 100]
      stochastic:
        window: 14
        smooth_window: 3
      rsi_windows: [14, 25, 50]
      macd:
        window_slow: 26
        window_fast: 12
        window_sign: 9

    # Return feature settings
    return_features:
      rolling_mean_windows: [5, 10, 15, 20]
      log_volume: true

  # Output settings
  output:
    save_processed: true
    save_normalized: true
    save_scalers: true
