# Configuration for forex prediction experiments

# Data configuration (preparation phase)
data:
  raw: data/raw/dukascopy-usdjpy-tick-2020-01-01-2024-12-31.csv

# Resampling configuration
resampling:
  type: time # 'time' or 'dollar'
  minutes: 1 # For time-based resampling
  threshold: 421558000000 # For dollar bar resampling
  symbol: "USDJPY"
  date_range:
    start_date: "20210101" # Format: YYYYMMDD
    end_date: "20241231" # Format: YYYYMMDD
  output:
    dir: data/resampled
    prefix: bars

events:
  # Event sampling configuration
  type: CUSUM # 'cusum' or 'volatility'
  threshold: 2.52e-04 # CUSUM threshold for event detection

# Preprocessing configuration
preprocessing:
  # Feature engineering settings
  features:
    add_returns: true
    add_technical_indicators: true
    add_time_features: true

    # Technical indicator settings
    technical_indicators:
      ema_windows: [5, 20, 50, 100]
      atr_windows: [14, 25, 50]
      adx_windows: [14]
      bollinger_bands:
        window: 20
        window_dev: 2
      donchian_channel:
        window: 20
      stochastic:
        window: 14
        smooth_window: 3
      rsi_windows: [14, 25, 50]
      macd:
        window_slow: 26
        window_fast: 12
        window_sign: 9

    # Return feature settings
    return_features:
      rolling_mean_windows: [5, 10, 15, 20]
      log_volume: true

  # Output settings
  output:
    save_processed: true
    save_normalized: true
    save_scalers: true
