# Data parameters
defaults:
  - data: cusum_classifier
  - model: transformer_classifier
  - _self_

# Training parameters
training:
  batch_size: 1024
  num_epochs: 100
  num_workers: 0
  val_split: 0.2
  shuffle: True
