# Data parameters
defaults:
  - data: next_bar_regr
  - model: baseline_regressor
  - _self_

hydra:
  sweeper:
    params:
      data: cusum_classifier
      model: baseline_classifier,transformer_classifier,lstm_classifier

# Training parameters
training:
  batch_size: 64
  num_epochs: 100
  num_workers: 0
  val_split: 0.2
  shuffle: True
data:
  features:
    - close_return
