# Data parameters
data:
  dataset_path: data/processed/USDJPY-1m-20210101-20241231-processed.pkl
  label_path: data/processed/direction_labels/USDJPY-1m-20210101-20241231-CUSUM-TB.pkl
  features:
    - log_fd_return
  target:
    - bin_class
  sequence_length: 60

# Model parameters
model:
  name: "lstm_classifier"
  n_hidden: 64
  n_layers: 2
  dropout: 0.1

# Training parameters
training:
  batch_size: 1024
  num_epochs: 100
  num_workers: 0
  val_split: 0.2
  shuffle: True

# Tuning
hyperparameter_tuning:
  num_layers: [3, 5]
