data:
  train_data_path: data/processed/USDJPY-15m-20210101-20231231_FEATURES.pkl
  test_data_path: data/processed/USDJPY-15m-20240101-20241231_FEATURES.pkl
defaults:
  - _self_
  - symbol: usdjpy
  - features: default

hydra:
  sweeper:
    params:
      symbol: eurusd, usdjpy, audusd, gbpusd

minutes:
  # - 1
  # - 3
  # - 5
  # - 10
  - 15

date:
  - from: 20210101
    to: 20231231
  # - from: 20230101
  #   to: 20231231
  - from: 20240101
    to: 20241231
