# Data parameters
defaults:
  - _self_
  - data: cusum_classifier
  - model: lstm_classifier

hydra:
  sweeper:
    params:
      data: cusum_classifier,zscore_classifier
      model: transformer_classifier,lstm_classifier

# Training parameters
training:
  batch_size: 1024
  num_epochs: 100
  num_workers: 0
  val_split: 0.2
  shuffle: True
