# Data parameters
data:
  dataset_path: data/processed/USDJPY-5m-20240101-20241231_processed.pkl
  label_path: data/direction_labels/USDJPY-5m-20240101-20241231-Z-SCORE-W100-2Z-TB.pkl
  features:
    - log_fd_return
  target:
    - ret
  sequence_length: 24

# Model parameters
model:
  name: "transformer_regressor"
  d_model: 64
  nhead: 4
  n_layers: 2
  dim_feedforward: 256
  dropout: 0.1
  pool: "last"

# Training parameters
training:
  batch_size: 1024
  num_epochs: 100
  num_workers: 0
  val_split: 0.2
  shuffle: True

# Tuning
hyperparameter_tuning:
  num_layers: [3, 5]
