# Data parameters
data:
  dataset_path: data/processed/USDJPY-5m-20240101-20241231_FEATURES.pkl
  label_path: data/direction_labels/USDJPY-5m-20240101-20241231-Z_SCORE_W100_2Z-TB.pkl
  features:
    - close
    - spread
    # Returns
    - close_log_return
    - close_fd_return
    # Trend
    - EMA_5
    - EMA_50
    # Volatility
    - ATRr_60
    # Momentum / Strength
    - RSI_14
    - ADX_14
    - DMP_14
    - DMN_14
    # Bollinger band position (multi-scale)
    - BBP_5_2.0_2.0
    - BBP_10_2.0_2.0
    - BBP_20_2.0_2.0
    # MACD momentum
    - MACDh_8_17_9
    # Time cyclicality
    - hour_sin
    - hour_cos
    - dow_sin
    - dow_cos
    - month_sin
    - month_cos
  target:
    - bin_class
  sequence_length: 60
  n_classes: 3

# Model parameters
model:
  name: "transformer_classifier"
  d_model: 64
  nhead: 4
  n_layers: 2
  dim_feedforward: 256
  dropout: 0.1
  pool: "mean"

# Training parameters
training:
  batch_size: 1024
  num_epochs: 100
  num_workers: 0
  val_split: 0.2
  shuffle: True

# Tuning
hyperparameter_tuning:
  num_layers: [3, 5]
