defaults:
  - data: sequence_regr
  - model: t2v_xfmr_regr_lf
  - _self_
hydra:
  sweeper:
    params:
      model: t2v_xfmr_regr, xfmr_regressor
# Training parameters
training:
  batch_size: 1024
  num_epochs: 100
  num_workers: 0
  val_split: 0.5
  shuffle: True
