defaults:
  - data: sequence_regr
  - model: t2v_transformer_regr
  - _self_
hydra:
  sweeper:
    params:
      model: t2v_transformer_regr, transformer_regressor
# Training parameters
training:
  batch_size: 1024
  num_epochs: 100
  num_workers: 0
  val_split: 0.5
  shuffle: True
