# Data parameters
defaults:
  - data: sequence_regr
  - model: t2v_xfmr_regr
  - _self_

hydra:
  sweeper:
    params:
      model.kernel_size: 2
      model.d_model: 64,128
      model.nhead: 4,8
      model.n_layers: 2,3,4
      model.dim_feedforward: 256
      model.pool: mean,last

# Training parameters
training:
  batch_size: 1024
  num_epochs: 100
  num_workers: 0
  val_split: 0.5
  shuffle: True
